# Generated by Django 2.2.9 on 2020-06-29 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20200629_0002'),
        ('registration', '0007_auto_20200626_1733'),
    ]

    operations = [
    ]
