# Generated by Django 2.2.9 on 2020-05-17 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_person_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='producer',
        ),
        migrations.AddField(
            model_name='movie',
            name='producers',
            field=models.ManyToManyField(blank=True, related_name='movies_produced', to='movies.Person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='movies_appeared', to='movies.Person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movies_directed', to='movies.Person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='returns',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='stars',
            field=models.ManyToManyField(blank=True, related_name='movies_starred', to='movies.Person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writers',
            field=models.ManyToManyField(blank=True, related_name='movies_written', to='movies.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='portraits/'),
        ),
    ]
