# Generated by Django 2.2.9 on 2020-05-19 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200517_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-create_time']},
        ),
    ]
