# Generated by Django 2.2.9 on 2020-06-29 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20200626_1733'),
        ('movies', '0010_auto_20200629_0002'),
    ]

    operations = [
    ]
