# Generated by Django 2.2.9 on 2020-06-29 05:27

from django.db import migrations
from testing_data.insert_testing_data import insert_testing_data


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_merge_20200629_0008'),
    ]

    operations = [
        migrations.RunPython(insert_testing_data)
    ]
